### PR TITLE
rust stable compatibility using ip_rfc crate

### PR DESCRIPTION
**Pull request by dnut**
I've made some tweaks to make the crate compatible with rust stable:
- switched from unstable `ip` feature to`ip_rfc` crate
- added import for FromStr for the tests (I guess this is in the prelude in nightly?)
- updated Containerfile to use rust stable image

The only reason you're using nightly is for the is_global function, which has been backported to a crate called ip_rfc that is dedicated to providing only that function. It's trivial to switch to that crate, which is what I've done here.

## Justification
It's not ideal to use nightly for production unless it has a huge benefit. You may encounter bugs, and long term usage  involves a higher maintenance cost.

While the nightly compiler is usually reasonably solid, bugs are much more common in nightly than stable. Also, if you enable nightly-only features, you may find there are a lot of known issues that have been unresolved for years. And things change a lot. If you just use whatever is the latest version of nightly, your code may randomly stop compiling. You'll need a solid process for locking and managing upgrades of the version of the nightly compiler used for the project to deal with this problem.

For example, I couldn't even get this repo to build using the latest nightly (1.73.0-nightly 04abc370b 2023-07-28):
```
$ cargo +nightly build
   Compiling proc-macro2 v1.0.56
   Compiling getrandom v0.2.9
   Compiling futures-core v0.3.28
   Compiling serde_derive v1.0.160
   Compiling syn v1.0.109
   Compiling serde v1.0.160
   Compiling tracing-core v0.1.30
   Compiling tokio v1.27.0
   Compiling pkg-config v0.3.26
   Compiling fnv v1.0.7
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /home/drew/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.56/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^

   Compiling mio v0.8.6
   Compiling socket2 v0.4.9
For more information about this error, try `rustc --explain E0635`.
error: could not compile `proc-macro2` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
```
Maybe this specific problem can be dealt with, I haven't looked into it, but my point is that you can avoid this entire class of problems by using rust stable.

### CODE REVIEW

**Comment by p1gp1g** [comment]
Thank you :)

**Comment by p1gp1g** [comment]
This has been squashed + merged, thanks
